spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 766040376800-mjk1v2pd53mdu6qak1m4nk0rj9tpatdi.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:8080/api/v1/auth/oauth2/success"
            authorization-grant-type: authorization_code
        provider:
          google:
            issuer-uri: https://accounts.google.com
  datasource:
    url: jdbc:mysql://localhost:3306/securityapplication
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true